# Generated by Django 4.1.3 on 2022-11-28 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45, unique=True)),
                ('last_name', models.CharField(max_length=45, unique=True)),
                ('role', models.CharField(max_length=45, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='team_photos/%y/%m/%d/')),
                ('facebook_link', models.URLField(max_length=100)),
                ('twitter_link', models.URLField(max_length=100)),
                ('google_link', models.URLField(max_length=100)),
                ('upload_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
