# Generated by Django 4.1.3 on 2022-11-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer', models.TextField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
